spring:
  application:
    name: microservice-consumer-purchase-ribbon-with-hystrix
server:
  port: 8081
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000