spring:
  application:
    name: microservice-consumer-purchase-feign-with-hystrix
server:
  port: 8082
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true