server:
  port: 8091
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-purchase-ribbon-with-hystrix,microservice-consumer-purchase-feign-with-hystrix
  clusterNameExpression: "'default'"